<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZyO2uxF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZyO2uxF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZyO2uxF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZyO2uxF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZyO2uxF\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZyO2uxF',
    'container.build_id' => '0c513339',
    'container.build_time' => 1721224025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZyO2uxF');
