<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerITvtM9i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerITvtM9i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerITvtM9i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerITvtM9i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerITvtM9i\App_KernelDevDebugContainer([
    'container.build_hash' => 'ITvtM9i',
    'container.build_id' => '5ad36e07',
    'container.build_time' => 1721119940,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerITvtM9i');
