<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHpb8OoL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHpb8OoL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHpb8OoL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHpb8OoL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHpb8OoL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hpb8OoL',
    'container.build_id' => 'cb099f0f',
    'container.build_time' => 1721394873,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHpb8OoL');
